;;; -*- Lisp -*-
(load "script-support")
(load-asdf)

(quit-on-error
 (setf asdf:*central-registry* '(*default-pathname-defaults*))
 (asdf:operate 'asdf:load-op 'test-samedir-modules)
 ;; test that it compiled
 (let* ((file1 (asdf:compile-file-pathname* "file1"))
        (file2 (asdf:compile-file-pathname* "file2"))
        (file1-date (file-write-date file1)))

   (format t "~&test samedir modules 1: ~S ~S~%" file1 file1-date)
   (assert file1-date)
   (assert (file-write-date file2))

   ;; and loaded
   (assert (symbol-value (find-symbol (symbol-name :*file1*) :test-package)))))

