;;; -*- Lisp -*-

(load-asdf)

(defparameter *fasl1* (test-fasl "file1.lisp"))
(defparameter *fasl2* (test-fasl "file2.lisp"))

(delete-file-if-exists *fasl1*)
(delete-file-if-exists *fasl2*)
(DBG "should load file1 but not file2")
(asdf:load-system :test3)
(assert (probe-file *fasl1*))
(assert (not (probe-file *fasl2*)))

(assert (not (component-property (find-system 'test3) :foo)))
(assert (equal (component-property (find-system 'test3) :prop1) "value"))
(setf (component-property (find-system 'test3) :foo) "bar")
(assert (equal (component-property (find-system 'test3) :foo) "bar"))
