;;; -*- Lisp -*-

;;;---------------------------------------------------------------------------
;;; Intended to test behaviors that we see when the deferred warnings check is
;;; NOT deferred.
;;; ---------------------------------------------------------------------------

(in-package :asdf-test)

(def-test-system :undefined-variables
  :components ((:file "fun-with-undefined-locals")))

(errors #+(or allegro clozure) compile-file-error
        #+(or cmu scl) null
        #+sbcl compile-failed-error
        (let ((*compile-file-warnings-behaviour* :error))
          (load-system :undefined-variables)))
(errors #+(or allegro clozure) compile-file-error
        #+(or cmu scl) null
        #+sbcl compile-failed-error
        (let ((*compile-file-warnings-behaviour* :warning))
          (load-system :undefined-variables :force t)))
