;;; -*- Lisp -*-

(defsystem :test-system-pathnames
  :pathname "sources/level1"
  :components
  ((:file "file1")
   (:file "file2" :pathname "level2/file2")
   (:static-file "level2/static.file")
   (:static-file "test-tmp.cl")))

(load-system 'test-system-pathnames)

(assert (find-package :test-package)
        () "package test-package not found")
(assert (find-symbol (symbol-name '*file-tmp*) :test-package)
        () "symbol `*file-tmp*` not found")
(assert (symbol-value (find-symbol (symbol-name '*file-tmp*) :test-package))
        () "symbol `*file-tmp*` has wrong value")

(assert (probe-file (test-fasl "sources/level1/file1"))
        () "compiled file not found")

(assert (find-symbol (symbol-name '*file-tmp2*) :test-package) nil
        "symbol `*file-tmp2*` not found")
(assert (symbol-value (find-symbol (symbol-name '*file-tmp2*) :test-package))
        () "symbol `*file-tmp2*` has wrong value")

(assert (probe-file (test-fasl "sources/level1/level2/file2"))
        () "compiled file not found")
