;;; -*- Lisp -*-
(load "script-support.lisp")
(load-asdf)

(in-package :asdf)
(use-package :asdf-test)

#+gcl (trace coerce-pathname)

(quit-on-error
 (format t "dpd: ~S~%f1: ~S~%" *default-pathname-defaults* (merge-pathnames* "file1"))

 (setf *central-registry* '(*default-pathname-defaults*))

 (operate 'load-op 'static-and-serial)
 (let* ((file1 (compile-file-pathname* "file1.lisp"))
        (file1-date (file-write-date file1)))
   (clear-system 'static-and-serial)
   (format t "file: ~S~%date: ~S~%" file1 file1-date)
   (assert file1-date)

   ;; date should stay same
   (sleep 1)
   (operate 'load-op 'static-and-serial)
   (assert (equal (file-write-date file1) file1-date))))
