;;; -*- Lisp -*-
(load "script-support.lisp")
(load-asdf)

(setf *central-registry* '(*default-pathname-defaults*))

(with-test ()
 (defsystem :versioned-system-1
   :pathname #.*default-pathname-defaults*
   :version "1.0")

 (defsystem :versioned-system-2
   :pathname #.*default-pathname-defaults*
   :version "1.1")

 (defsystem :versioned-system-3
   :pathname #.*default-pathname-defaults*
   :version "1.2")

 (flet ((test (name v &optional (true t))
          (or (eq true (version-satisfies (find-system name) v))
              (error "no satisfaction: ~S version ~A not ~A" name v true))))
   (test :versioned-system-1 "1.0")
   (test :versioned-system-2 "1.0")
   (test :versioned-system-3 "2.0" nil)))
