;;; -*- Lisp -*-

(defparameter *fasl1* (test-fasl "file1.lisp"))
(defparameter *fasl2* (test-fasl "file2.lisp"))

(delete-file-if-exists *fasl1*)
(delete-file-if-exists *fasl2*)
(DBG "should load file1 but not file2")

;;; Use REQUIRE where we boast integration, load-system where not.
#+(or abcl clisp clozure cmu ecl mkcl sbcl)
(require :test3)
#-(or abcl clisp clozure cmu ecl mkcl sbcl)
(load-system :test3)

(assert (probe-file *fasl1*))
(assert (not (probe-file *fasl2*)))
