;;; -*- Lisp -*-
(load "script-support.lisp")
(load-asdf)

(in-package :asdf)
(use-package :asdf-test)

(quit-on-error
 (let* ((asd (subpathname *test-directory* "test-multiple.asd"))
        (tmp (subpathname *test-directory* "../tmp/"))
        (asd2 (subpathname tmp "test-multiple-too.asd"))
        (file4 (compile-file-pathname* "file4")))
   (setf *central-registry* `(,*test-directory* ,tmp))
   (assert (= 0 (run-shell-command
                 (format nil "/bin/ln -sf ~A ~A"
                         (native-namestring asd)
                         (native-namestring asd2)))))
   (oos 'load-source-op 'test-multiple-too)
   (assert (symbol-value (find-symbol (string :*file3*) :test-package)))
   (load-system 'test-multiple-free)
   (assert (asdf::probe-file* file4))))
