;;; -*- Lisp -*-

(clear-system :test-deferred-warnings)
(def-test-system :test-deferred-warnings
  :serial t
  :components ((:file "undefined-function")
               (:file "file1")))
(DBG :tdw0 *compile-file-warnings-behaviour*)
(assert
 (handler-case
     (let ((*compile-file-warnings-behaviour* :ignore))
       (load-system :test-deferred-warnings :force t)
       t)
   (error (c)
     (DBG :cfwbi c)
     nil)))

(DBG :tdw1 *warnings-file-type*)
(assert
 (handler-case
     (let ((*warnings-file-type* nil))
       (load-system :test-deferred-warnings :force t)
       t)
   (error ()
     (DBG :wftn c)
     nil)))

#+(or clozure cmu sbcl scl)
(assert
 (handler-case
     (let ((*compile-file-warnings-behaviour* :error))
       (load-system :test-deferred-warnings :force t)
       nil)
   (compile-warned-error () t)))

#+(or clozure cmu sbcl scl)
(assert
 (handler-case
     (let ((*compile-file-warnings-behaviour* :error))
       (perform 'compile-op :test-deferred-warnings)
       nil)
   (compile-warned-error () t)))
