;;; -*- Lisp -*-

(unless (or #+(or (and clisp os-unix) clozure cmu
                  (and ecl (not ecl-bytecmp) (not os-macosx)) lispworks mkcl sbcl scl) t)
  (DBG "Creating executables is not supported on your CL implementation")
  (leave-test "Skipping test" 0))

(DBG "build sample-system. Should load from sample-system/")
(setf *central-registry* (list (subpathname *test-directory* "sample-system/")))

(make-build 'sample-system
            :type :program :monolithic t
            #+(and ecl (not os-windows)) :name-suffix #+(and ecl (not os-windows)) ""
            #+allegro :name-suffix #+allegro ".exe" ;; but in allegro 9.0 pathname translation of :unspecific(!)
            #+ecl :epilogue-code #+ecl '(println "blue sky"))
