;;; -*- Lisp -*-

;;; test system definition reloading if touched
;;; system that canNOT be found using *system-definition-search-functions*

(load "script-support.lisp")
(load-asdf)
(with-test ()
 (flet ((system-load-time (name)
          (let ((data (asdf::system-registered-p name)))
            (when data
              (car data)))))
   (setf asdf:*central-registry* nil)
   (load "test1.asd")
   (assert (find-system :test1))
   (let ((date1 (system-load-time :test1))
         (file "test1.asd"))
     (assert date1)
     (assert file)
     (sleep 2)
     (touch-file file)
     (asdf:find-system :test1)
     (let ((date2 (system-load-time :test1)))
       (assert date2)
       (assert (> date2 date1))))))
