;;; -*- Lisp -*-

(unless (or #+(or (and clisp os-unix) clozure cmucl
                  (and ecl (not ecl-bytecmp)) lispworks mkcl sbcl scl) t)
  (DBG "Creating executables is not supported on your CL implementation")
  (leave-test "Skipping test" 0))

(DBG "build sample-system. Should load from sample-system/")
(setf *central-registry* (list (subpathname *test-directory* "sample-system/")))

#+lispworks (lispworks:load-all-patches)

(make-build 'sample-system
            :type :program :monolithic t
            #+ecl :epilogue-code #+ecl '(println "blue sky"))
