;;; -*- Lisp -*-
(load "script-support.lisp")
(load-asdf)

#+gcl (trace load compile-file asdf:perform asdf::perform-plan)
(with-test ()
 (setf asdf:*central-registry* (list (asdf::subpathname *test-directory* "xach-foo-1/")))
 (asdf:load-system "foo")
 (assert (symbol-value (find-symbol (string :loaded) :first-version)))
 (setf asdf:*central-registry* (list (asdf::subpathname *test-directory* "xach-foo-2/")))
 (asdf:load-system "foo")
 (assert (symbol-value (find-symbol (string :loaded) :second-version)))
 (assert (eql 42 (funcall (find-symbol (string :wtf) :second-version)))))
