;;-*- Lisp -*-

(defun current-system-source-file (x)
  (system-source-file (asdf::registered-system x)))

(with-asdf-cache ()
  (DBG "loading test-mutual-redefinition-1")
  (let ((warned-p nil))
    (handler-bind ((bad-system-name (lambda (c)
                                      (assert-equal (component-name c) "test-mutual-redefinition-2")
                                      (assert-equal (pathname-name (system-source-file c)) "test-mutual-redefinition-1")
                                      (setf warned-p t))))
      (load-system 'test-mutual-redefinition-1))
    (assert warned-p))
  (assert-pathname-equal
   (test-source "test-mutual-redefinition-1.asd")
   (current-system-source-file "test-mutual-redefinition-1"))
  (assert-pathname-equal
   (test-source "test-mutual-redefinition-1.asd")
   (current-system-source-file "test-mutual-redefinition-2"))

  (DBG "loading test-mutual-redefinition-2 in the same cache session")
  (load-system 'test-mutual-redefinition-2)
  (assert-pathname-equal
   (test-source "test-mutual-redefinition-1.asd")
   (current-system-source-file "test-mutual-redefinition-1"))
  (assert-pathname-equal
   (test-source "test-mutual-redefinition-1.asd")
   (current-system-source-file "test-mutual-redefinition-2"))

  (with-asdf-cache (:override t)
    (DBG "loading test-mutual-redefinition-2 in a different cache session")
    (load-system 'test-mutual-redefinition-2)
    (assert-pathname-equal
     (test-source "test-mutual-redefinition-2.asd")
     (current-system-source-file "test-mutual-redefinition-1"))
    (assert-pathname-equal
     (test-source "test-mutual-redefinition-2.asd")
     (current-system-source-file "test-mutual-redefinition-2"))))
