;;; -*- Lisp -*-
(load "script-support.lisp")
(load-asdf)

(with-test ()
 (asdf:load-system 'test-system-pathnames)
 (assert (find-package :test-package)
         () "package test-package not found")
 (assert (find-symbol (symbol-name '*file-tmp*) :test-package)
         () "symbol `*file-tmp*` not found")
 (assert (symbol-value (find-symbol (symbol-name '*file-tmp*) :test-package))
         () "symbol `*file-tmp*` has wrong value")

 (assert (probe-file
          (asdf::apply-output-translations
           (asdf::merge-pathnames*
            (asdf::make-pathname*
             :name "file1"
             :type (asdf::fasl-type)
             :directory '(:relative "sources" "level1"))
            *test-directory*)))
         () "compiled file not found")

 (assert (find-symbol (symbol-name '*file-tmp2*) :test-package) nil
         "symbol `*file-tmp2*` not found")
 (assert (symbol-value (find-symbol (symbol-name '*file-tmp2*) :test-package))
         nil "symbol `*file-tmp2*` has wrong value")

 (assert (probe-file
          (asdf::apply-output-translations
           (asdf::merge-pathnames*
            (asdf::make-pathname*
             :name "file2"
             :type (asdf::fasl-type)
             :directory '(:relative "sources" "level1" "level2")))))
         nil "compiled file not found"))
