;;; -*- Lisp -*-

;;;---------------------------------------------------------------------------
;;; Intended to test behaviors that we see when the deferred warnings check is
;;; NOT deferred.
;;; ---------------------------------------------------------------------------

(in-package :asdf-test)

(def-test-system :undefined-variables
  :components ((:file "fun-with-undefined-locals")))


#+(or allegro clozure cmu sbcl scl)
(progn
  (errors #+(or allegro clozure) compile-file-error
          #+(or cmu sbcl scl) null
          (let ((*compile-file-warnings-behaviour* :error))
            (load-system :undefined-variables)))
  (errors #+(or allegro clozure) compile-file-error
          #+(or cmu sbcl scl) null
          (let ((*compile-file-warnings-behaviour* :warning))
            (load-system :undefined-variables :force t))))
