;;; -*- Lisp -*-
(load "script-support")
(load-asdf)
(setf asdf:*central-registry* '(*default-pathname-defaults*))

(defpackage :test-version-system
  (:use :cl :asdf))

(in-package :test-version-system)

(cl-user::quit-on-error
 (defsystem :versioned-system-1
   :pathname #.*default-pathname-defaults*
   :version "1.0")

 (defsystem :versioned-system-2
   :pathname #.*default-pathname-defaults*
   :version "1.1")

 (defsystem :versioned-system-3
   :pathname #.*default-pathname-defaults*
   :version "1.2")

 (flet ((test (name v &optional (true t))
          (or (eq true (asdf::version-satisfies (find-system name) v))
              (error "no satisfaction: ~S version ~A not ~A" name v true))))
   (test :versioned-system-1 "1.0")
   (test :versioned-system-2 "1.0")
   (test :versioned-system-3 "2.0" nil))

 )