;;; -*- Lisp -*-
;;; -*- Lisp -*-
(load "script-support")
(load-asdf)
(in-package :asdf)
(cl-user::quit-on-error
 (setf asdf:*central-registry* '(*default-pathname-defaults*))
 (assert (not (component-property (find-system 'test3) :foo)))
 (assert (equal (component-property (find-system 'test3) :prop1) "value"))
 (setf (component-property (find-system 'test3) :foo) "bar")
 (assert (equal (component-property (find-system 'test3) :foo) "bar"))
 )