;;; -*- Lisp -*-
(load "script-support.lisp")
(load-asdf)

(with-test ()
 (setf asdf:*central-registry* '(*default-pathname-defaults*))
 (DBG "loading test-samedir-modules")
 (asdf:operate 'asdf:load-op 'test-samedir-modules)
 (let* ((file1 (asdf:compile-file-pathname* "file1"))
        (file2 (asdf:compile-file-pathname* "file2"))
        (file1-date (file-write-date file1)))

   (DBG "test that it compiled" file1 file1-date)
   (assert file1-date)
   (assert (file-write-date file2))

   (DBG "and loaded")
   (assert (symbol-value (find-symbol (symbol-name :*file1*) :test-package)))))
