;;; -*- Lisp -*-

;;; test retrying finding location of an ASDF system.


(in-package asdf-test)
(defparameter *old-registry* asdf:*central-registry*)
;;(defparameter *search-table* (hash-table->alist asdf::*source-registry*))
;;(pprint *search-table*)
;;(terpri)
(assert (asdf:find-system "test-asdf/force1"))

(defun clear-caches-and-search ()
  (setf asdf:*central-registry* nil)
  (asdf/find-system:clear-defined-system "test-asdf/force1"))

(DBG "Clearing the caches and finding.")
(clear-caches-and-search)
(assert (not (asdf:find-system "test-asdf/force1" nil)))
(let (tried-once)
  (handler-bind
   ((asdf:missing-dependency-of-version
     (lambda (c)
       ;; Nothing Quicklisp can do to recover from this, so
       ;; just resignal
       (error c)))
    (asdf:missing-dependency
     (lambda (c)
       (if (not tried-once)
           (let ((missing (asdf::missing-requires c)))
             (assert (equal missing "test-asdf/force1"))
             (setf tried-once t)
             (DBG "Trying to reset the central registry and retry.")
             (setf asdf:*central-registry* *old-registry*)
             (asdf:find-system missing))
         ;; avoid infinite looping
         (error c)))))
 (asdf:find-system "test-asdf/force1")))

(DBG "Refinding test successful.")

(DBG "Now trying LOAD-SYSTEM with refinding.")
(clear-caches-and-search)
(trace find-system)
(trace find-component)
(trace asdf::component-find-path)
(trace operate)
(let (tried-once)
  (flet ((handle-missing (c)
                         (if (not tried-once)
           (let ((missing (asdf::missing-requires c)))
             (assert (equal missing "test-asdf/force1"))
             (setf tried-once t)
             (DBG "Trying to reset the central registry and retry.")
             (setf asdf:*central-registry* *old-registry*)
             (unless (find-restart 'asdf:reinitialize-source-registry-and-retry)
               (error "Expected REINITIALIZE-SOURCE-REGISTRY-AND-RETRY restart not found."))
             (DBG "Before invoking restart, CENTRAL-REGISTRY is:~%~T~S"
                  asdf:*central-registry*)
             (invoke-restart 'asdf:reinitialize-source-registry-and-retry)
             (DBG "After invoking restart, CENTRAL-REGISTRY is:~%~T~S"
                  asdf:*central-registry*))
         ;; avoid infinite looping
         (error c))))
  (handler-bind
   ((asdf:missing-dependency-of-version
     (lambda (c)
       ;; Nothing Quicklisp can do to recover from this, so
       ;; just resignal
       (error c)))
    (asdf:missing-dependency
     (lambda (c)
       (DBG "Catching MISSING-DEPENDENCY condition:" tried-once)
       (handle-missing c)))
    (asdf:missing-component
     (lambda (c)
       (DBG "Catching MISSING-COMPONENT condition:" tried-once)
       (handle-missing c))))
 (asdf:load-system "test-asdf/force1"))))
