;;; -*- Lisp -*-
(load "script-support.lisp")
(load-asdf)

(quit-on-error
 (setf asdf:*central-registry* '(*default-pathname-defaults*))
 (asdf:load-system 'test-weakly-depends-on)
 ;; test that it compiled
 (let* ((file1 (asdf:compile-file-pathname* "file1"))
        (file1-date (file-write-date file1)))

   (format t "~&test1 1: ~S ~S~%" file1 file1-date)
   (assert file1-date)
   ;; and loaded
   (assert (symbol-value (find-symbol (symbol-name :*file1*) :test-package)))))
