;;; -*- Lisp -*-

(load "script-support")
(load-asdf)

(quit-on-error
 (setf asdf:*central-registry* '(*default-pathname-defaults*))
 (assert (handler-case
             (progn
               (asdf:load-system 'deprecated :force t)
               nil
               )
           (asdf:deprecated-system-warning () t)))
 (assert (handler-case
             (progn
               (asdf:load-system 'test1 :force t)
               t
               )
           (asdf:deprecated-system-warning () nil))))
