;;; -*- Lisp -*-
(load "script-support")
(load "../asdf")
(quit-on-error 
 (setf asdf:*central-registry* '(*default-pathname-defaults*))
 (asdf:operate 'asdf:load-op 'test-module-pathnames))

(quit-on-error 
 (assert (find-package :test-package) nil
	 "package test-package not found")
 (assert (find-symbol (symbol-name '*file-tmp*) :test-package) nil
	 "symbol `*file-tmp*` not found")
 (assert (symbol-value (find-symbol (symbol-name '*file-tmp*) :test-package))
	 nil "symbol `*file-tmp*` has wrong value")
 (assert (probe-file (merge-pathnames 
		      (make-pathname 
		       :name "file1"
		       :type (pathname-type (compile-file-pathname "x"))
		       :directory '(:relative "sources" "level1"))))
	 nil "compiled file not found")

 (assert (find-symbol (symbol-name '*file-tmp2*) :test-package) nil
	 "symbol `*file-tmp2*` not found")
 (assert (symbol-value (find-symbol (symbol-name '*file-tmp2*) :test-package))
	 nil "symbol `*file-tmp2*` has wrong value")
 (assert (probe-file (merge-pathnames 
		      (make-pathname 
		       :name "file2"
		       :type (pathname-type (compile-file-pathname "x"))
		       :directory '(:relative "sources" "level1" "level2"))))
	 nil "compiled file not found"))
