{include resources/header.md}

{set-property title "Getting Started | ASDF"}
{set-property docs-package asdf}

See the first three sections of the
[manual][]

{docs-index all}

{include resources/footer.md}
