{include resources/header.md}

<div class="contents">
<div class="system-links">
  * [Mailing Lists][]
  * [Getting it][]
  * [Changelog][]
  * [System Tests][tests]
</div>

<div class="system-description">

### What it is

ASDF is a tool for describing how source files are organized:
what depends on which and when. I.e., it is *A*nother
*S*ystem *D*efinition *F*acility.

If you want to use ASDF with other people's systems, see the
[getting started][getting-started] guide. For details on
defining your own systems, you should browse the [manual][].

<a id="mailing-lists"></a>

### Mailing Lists

  * [asdf-devel][]: A list for questions, patches,
    bug reports, and so on; It's for everything.

<a href="downloads"></a>

### Where is it

Though they may lag behind the version here, ASDF comes
bundled with most Lisps. To get the greatest and latest, you
can:

* download just the source for [asdf.lisp][],
* download the [tarball][] to get all bells and whistles,
* pull the latest from our git repository

        git clone http://common-lisp.net/project/asdf/asdf.git

{remark * use [ASDF-install][] to update yourself }

### Contributing

We're still working out the details. For now, send email to
gwking@metabang.com or the project [mailing-list][asdf-devel]
with questions or patches.

    
<a id="news"></a>

### What is happening

 * Saturday; June 6, 2009 - updated website and added [oos][]
   shortcuts like [load-system][].

 * Sunday; May 3, 2009 - moving towards git and Common-Lisp.net


</div>
{include resources/footer.md}
</div>


