{include resources/ug-header.md}
{set-property title "LIFT User's Guide"}
{set-property style-sheet user-guide}
{set-property docs-package lift}

# ASDF User's Guide

# Table of Contents 

{table-of-contents :start 2 :depth 3}

## Introduction

## Indices

### Index of Functions

{docs-index function}

### Index of variables

{docs-index variable}

### Index of Macros

{docs-index macro}

### Full symbol index

{docs-index :all}

<hr>

#### Glossary

{glossary}


#### Footnotes

{footnotes}

{include resources/ug-footer.md}
